// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7PEoQFwaEpMQdi1WHWb_qGDb-cJ4KyCY',
    appId: '1:51903881089:web:1722aecace84d1d6089280',
    messagingSenderId: '51903881089',
    projectId: 'alzheimer-app-a6022',
    authDomain: 'alzheimer-app-a6022.firebaseapp.com',
    storageBucket: 'alzheimer-app-a6022.appspot.com',
    measurementId: 'G-8ZDLS3VWF2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe79XcrQgySVq9pwQyBX5Mc76i2AyiVWE',
    appId: '1:51903881089:android:b6c3c98a99d53ae5089280',
    messagingSenderId: '51903881089',
    projectId: 'alzheimer-app-a6022',
    storageBucket: 'alzheimer-app-a6022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuG4jrgr-aKswJyYehY_zXWxOTRn9S6vQ',
    appId: '1:51903881089:ios:6684c271f572ce57089280',
    messagingSenderId: '51903881089',
    projectId: 'alzheimer-app-a6022',
    storageBucket: 'alzheimer-app-a6022.appspot.com',
    iosClientId: '51903881089-q6pqf1pq4nc9hfgtmm0jlv9f65hjadge.apps.googleusercontent.com',
    iosBundleId: 'com.example.alzheimerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuG4jrgr-aKswJyYehY_zXWxOTRn9S6vQ',
    appId: '1:51903881089:ios:6684c271f572ce57089280',
    messagingSenderId: '51903881089',
    projectId: 'alzheimer-app-a6022',
    storageBucket: 'alzheimer-app-a6022.appspot.com',
    iosClientId: '51903881089-q6pqf1pq4nc9hfgtmm0jlv9f65hjadge.apps.googleusercontent.com',
    iosBundleId: 'com.example.alzheimerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7PEoQFwaEpMQdi1WHWb_qGDb-cJ4KyCY',
    appId: '1:51903881089:web:aba1099e3312e520089280',
    messagingSenderId: '51903881089',
    projectId: 'alzheimer-app-a6022',
    authDomain: 'alzheimer-app-a6022.firebaseapp.com',
    storageBucket: 'alzheimer-app-a6022.appspot.com',
    measurementId: 'G-2EWPXQ55W6',
  );
}
