name: Build Web

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create .env file
        run: |
          cat > assets/.env << EOF
          FIREBASE_API_KEY_WEB=${{ secrets.FIREBASE_API_KEY_WEB }}
          FIREBASE_API_KEY_ANDROID=${{ secrets.FIREBASE_API_KEY_ANDROID }}
          FIREBASE_API_KEY_IOS=${{ secrets.FIREBASE_API_KEY_IOS }} 
          FIREBASE_API_KEY_MACOS=${{ secrets.FIREBASE_API_KEY_MACOS }}
          FIREBASE_API_KEY_WINDOWS=${{ secrets.FIREBASE_API_KEY_WINDOWS }}

          FIREBASE_APP_ID_WEB=${{ secrets.FIREBASE_APP_ID_WEB }}
          FIREBASE_APP_ID_ANDROID=${{ secrets.FIREBASE_APP_ID_ANDROID }}
          FIREBASE_APP_ID_IOS=${{ secrets.FIREBASE_APP_ID_IOS }}
          FIREBASE_APP_ID_MACOS=${{ secrets.FIREBASE_APP_ID_MACOS }}
          FIREBASE_APP_ID_WINDOWS=${{ secrets.FIREBASE_APP_ID_WINDOWS }}

          FIREBASE_MESSAGE_SENDER_ID=${{ secrets.FIREBASE_MESSAGE_SENDER_ID }}
          FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_MEASUREMENT_ID=${{ secrets.FIREBASE_MEASUREMENT_ID }}
          FIREBASE_IOS_CLIENT_ID=${{ secrets.FIREBASE_IOS_CLIENT_ID }}
          FIREBASE_IOS_BUNDLE_ID=${{ secrets.FIREBASE_IOS_BUNDLE_ID }}
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          EOF

      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - uses: erickzanardo/flutter-gh-pages@v7
        with:
          basehref: /easymemo/
